// SPDX-License-Identifier: GPL-2.0-or-later

#ifndef RA_NET_REGS_H
#define RA_NET_REGS_H

#define RA_NET_TX_FIFO_MIN_SPACE_AVAILABLE	1536

#define RA_NET_MAX_MTU				1500

/* 2 Bytes padding before MAC addresses to keep IP address 32bit aligned */
#define RA_NET_TX_PADDING_BYTES			2
#define RA_NET_RX_PADDING_BYTES			2

#define RA_NET_MAC_ADDR_L			0x0000
#define RA_NET_MAC_ADDR_H			0x0004

#define RA_NET_MAC_RX_CTRL			0x0008
#define RA_NET_MAC_RX_CTRL_PROMISCUOUS_EN	BIT(31)
#define RA_NET_MAC_RX_CTRL_MULTICAST_EN		BIT(0)

#define RA_NET_VLAN_CTRL			0x000c
#define RA_NET_VLAN_CTRL_VLAN_EN		BIT(31)

#define RA_NET_AUTO_SPEED_CTRL			0x0014
#define RA_NET_AUTO_SPEED_MANUAL		BIT(0)
#define RA_NET_AUTO_SPEED_10			(0U << 1)
#define RA_NET_AUTO_SPEED_100			(1U << 1)
#define RA_NET_AUTO_SPEED_1000			(2U << 1)
#define RA_NET_AUTO_SPEED_TX_INHIBIT		BIT(3)

#define RA_NET_MAC_FEATURES			0x001c
#define RA_NET_MAC_FEATURE_VLAN			BIT(0)

#define RA_NET_CTR_RESET			0x0020
#define RA_NET_FIFO_ERR_CNT			0x0024
#define RA_NET_RX_UNICAST_PKT_CNT		0x0028
#define RA_NET_RX_MULTICAST_PKT_CNT		0x002C
#define RA_NET_RX_BROADCAST_PKT_CNT		0x0030
#define RA_NET_RX_DROPPED_FRAMES_CNT		0x0034
#define RA_NET_RX_FCS_ERR_CNT			0x0038

#define RA_NET_TX_UNICAST_PKT_CNT		0x003C
#define RA_NET_TX_MULTICAST_PKT_CNT		0x0040
#define RA_NET_TX_BROADCAST_PKT_CNT		0x0044
#define RA_NET_TX_PAD_PKT_CNT			0x0048
#define RA_NET_TX_OVERSIZE_PKT_CNT		0x004C

#define RA_NET_MDIO_DATA			0x0050

#define RA_NET_MDIO_CTRL			0x0054
#define RA_NET_MDIO_CTRL_WRITE			BIT(1)
#define RA_NET_MDIO_CTRL_BUSY			BIT(2)
#define RA_NET_MDIO_CTRL_ADDR_MASK		0x001f0000
#define RA_NET_MDIO_CTRL_ADDR_SHIFT		16
#define RA_NET_MDIO_CTRL_PHY_ADDR_MASK		0x03e00000
#define RA_NET_MDIO_CTRL_PHY_ADDR_SHIFT		21

#define RA_NET_VLAN_CTRL_ARRAY			0x0060

/* Packet Processor / PTP timestamping */

#define RA_NET_RAV_CORE_VERSION			0x0400
#define RA_NET_RAV_CORE_VERSION_MASK		0x0000ffff

#define RA_NET_CONFIG				0x0400
#define RA_NET_CONFIG_MASK			0xffff0000
#define RA_NET_CONFIG_USE_SRAM_E2		0x80000000
#define RA_NET_CONFIG_USE_SRAM_E2_SHIFT		31

#define RA_NET_PP_CNT_RST			0x404

#define RA_NET_PP_CNT_RX_PARSED			0x408
#define RA_NET_PP_CNT_RX_QUEUE_ERR		0x40c
#define RA_NET_PP_CNT_RX_IP_CHK_ERR		0x410
#define RA_NET_PP_CNT_RX_STREAM_DROP		0x414
#define RA_NET_PP_CNT_RX_STREAM			0x0418
#define RA_NET_PP_CNT_RX_LEGACY			0x041c

#define RA_NET_PP_CNT_TX_STREAM			0x0424
#define RA_NET_PP_CNT_TX_LEGACY			0x0428
#define RA_NET_PP_CNT_TX_STREAM_LOST		0x042c

#define RA_NET_PP_CNT_UDP_FILTER_CTRL		0x0430
#define RA_NET_PP_CNT_UDP_THROTTLE		0x0434

#define RA_NET_RTP_GLOBAL_OFFSET		0x0438

#define RA_NET_PP_CONFIG			0x0440
#define RA_NET_PP_CONFIG_ENABLE_PTP_TIMESTAMPS	BIT(0)

#define RA_NET_PP_IRQS				0x0444
#define RA_NET_PP_IRQ_DISABLE			0x0448
#define RA_NET_PP_IRQ_PTP_TX_TS_IRQ_AVAILABLE	BIT(0)

#define RA_NET_PTP_DELAY_ADJUST_1		0x044C
#define RA_NET_PTP_DELAY_ADJUST_2		0x0450

#define RA_NET_PTP_TX_TS_CNT			0x0454
#define RA_NET_TX_TIMESTAMP_FIFO		0x0458

/* Legacy traffic interface */

#define RA_NET_IRQS				0x0600
#define RA_NET_IRQ_DISABLE			0x0604

#define RA_NET_ID				0x0608
#define RA_NET_ID_VALUE				0xfacedeed
#define RA_NET_ID_VALUE_2			0xfaced00f

#define RA_NET_TX_STATE				0x060C
#define RA_NET_TX_CONFIG			0x0610
#define RA_NET_TX_FIFO_SPACE_AV_BYTECNT		0x0614
#define RA_NET_RX_STATE				0x0618
#define RA_NET_RX_CONFIG			0x061C
#define RA_NET_RX_PACKET_DROPPED_CNT		0x0620

#define RA_NET_RX_FIFO				0x0700	/* R */
#define RA_NET_TX_FIFO				0x0700	/* W */

#define RA_NET_IRQ_TX_EMPTY			BIT(0)
#define RA_NET_IRQ_TX_SPACE_AVAILABLE		BIT(1)
#define RA_NET_IRQ_TX_TIMESTAMP_AVAILABLE	BIT(2)
#define RA_NET_IRQ_RX_PACKET_AVAILABLE		BIT(4)
#define RA_NET_IRQ_RX_OVERRUN			BIT(8)

#define RA_NET_TX_STATE_SPACE_AVAILABLE_MASK	0x00001fff

#define RA_NET_TX_CONFIG_TX_BYTECNT_MASK	0x000007ff
#define RA_NET_TX_CONFIG_TIMESTAMP_PACKET	BIT(31)

#define RA_NET_RX_STATE_PACKET_LEN_MASK		0x000007FF
#define RA_NET_RX_STATE_PACKET_HAS_PTP_TS	BIT(31)

#endif /* RA_NET_REGS_H */
